# Generated by Django 5.2 on 2026-03-03 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('chess.com', 'Chess.com'), ('lichess', 'Lichess')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pgn', models.TextField(help_text='Full PGN of the game')),
                ('played_at', models.DateTimeField()),
                ('white', models.CharField(max_length=100)),
                ('black', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=10)),
                ('my_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('my_rating', models.IntegerField(blank=True, null=True)),
                ('opponent_rating', models.IntegerField(blank=True, null=True)),
                ('opening_eco', models.CharField(blank=True, max_length=10)),
                ('opening_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insights', models.JSONField(default=dict)),
                ('voice_notes', models.TextField(blank=True, null=True)),
                ('buddy_advice', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating', models.IntegerField(default=800)),
                ('target_rating', models.IntegerField(default=1500)),
                ('preferred_voice', models.CharField(default='default', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeaknessPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('frequency', models.IntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('severity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
