# Generated by Django 5.2 on 2026-03-03 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('new_practice', 'New Practice Game'), ('game_review', 'Redo Uploaded Game')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_pgn', models.TextField(blank=True)),
                ('current_move_number', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('position_fen', models.CharField(max_length=100)),
                ('user_thought', models.TextField()),
                ('buddy_response', models.TextField(blank=True, null=True)),
                ('voice_transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='core.practicesession')),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
    ]
