# Generated by Django 5.2 on 2026-03-04 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_practicesession_userreflection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreflection',
            name='practice_session',
        ),
        migrations.RemoveField(
            model_name='weaknesspattern',
            name='user',
        ),
        migrations.RenameField(
            model_name='gameanalysis',
            old_name='created_at',
            new_name='analyzed_at',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='buddy_advice',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='insights',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='voice_notes',
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='accuracy_black_pct',
            field=models.FloatField(blank=True, help_text="Black's overall accuracy %", null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='accuracy_white_pct',
            field=models.FloatField(blank=True, help_text="White's overall accuracy %", null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='accuracy_yours_pct',
            field=models.FloatField(blank=True, help_text='Your side accuracy %', null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='avg_centipawn_loss',
            field=models.FloatField(blank=True, help_text='Average CPL for the game', null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='avg_cpl_yours',
            field=models.FloatField(blank=True, help_text='Your average CPL', null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='avg_time_per_move_yours_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='blunder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='buddy_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='engine_depth_used',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='inaccuracy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='main_weakness_tag',
            field=models.CharField(blank=True, help_text="e.g. 'middlegame tactics', 'time trouble'", max_length=80),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='mistake_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='opening_performance',
            field=models.CharField(blank=True, help_text="e.g. 'solid in Ruy Lopez', 'weak in Sicilian'", max_length=80),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='time_pressure_moves',
            field=models.IntegerField(default=0, help_text='Moves where you had <10s and position was critical'),
        ),
        migrations.CreateModel(
            name='MoveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.IntegerField()),
                ('move_number', models.IntegerField()),
                ('player', models.CharField(max_length=5)),
                ('is_your_move', models.BooleanField()),
                ('san', models.CharField(max_length=10)),
                ('uci', models.CharField(max_length=5)),
                ('fen_after', models.CharField(max_length=100)),
                ('eval_before', models.FloatField(blank=True, help_text='Centipawns before move (positive = white advantage)', null=True)),
                ('eval_after', models.FloatField(blank=True, null=True)),
                ('centipawn_loss', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, choices=[('book', 'Book move / theory'), ('best', 'Best move'), ('excellent', 'Excellent'), ('good', 'Good'), ('inaccuracy', 'Inaccuracy'), ('mistake', 'Mistake'), ('blunder', 'Blunder'), ('missed_win', 'Missed win')], max_length=20)),
                ('top_engine_moves', models.JSONField(blank=True, default=list, help_text='Example: [{"uci":"d2d4","score":0.45,"depth":18}, ...]')),
                ('themes', models.JSONField(blank=True, default=list, help_text='["development", "pawn_break", "hanging_piece", "fork", "pin", ...]')),
                ('short_note', models.CharField(blank=True, max_length=120)),
                ('game_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_analyses', to='core.gameanalysis')),
            ],
            options={
                'verbose_name_plural': 'Move Analyses',
                'ordering': ['ply'],
            },
        ),
        migrations.DeleteModel(
            name='PracticeSession',
        ),
        migrations.DeleteModel(
            name='UserReflection',
        ),
        migrations.DeleteModel(
            name='WeaknessPattern',
        ),
    ]
