# Generated by Django 5.2 on 2026-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userreflection_practice_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanalysis',
            name='decision_game_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='meta_coach_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='tactic_game_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='weakness_game_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='decision_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='decision_model_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='decision_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='tactic_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='tactic_model_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='tactic_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='weakness_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='weakness_model_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='weakness_summary',
            field=models.TextField(blank=True),
        ),
    ]
